### ISSUE TITLE
name' is not a valid attribute for a Block

### ISSUE THREAD

**Issue by minscof** [benasse/sparrow#5]
I try to install on ubuntu, and I have this error 👍 

`ERROR! 'name' is not a valid attribute for a Block

The error appears to have been in '/home/user/wazo-ansible/roles/preflight_checks/tasks/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Preflight checks
  ^ here
`

Can you help ?

**Comment by benasse** [comment]
Unfortunately, I never tried to install wazo on ubuntu, I don't think a lot of people managed to do it.
I advise rather to install wazo/sparrow from a fresh debian/raspbian installation.

**Comment by benasse** [comment]
I close the issue, do not hesitate to share your experience if you have successfully installed sparrow on ubuntu. That interests me.

I haven't looked too much but the version of ansible present on ubuntu may be too old.
