### ISSUE TITLE
error durin install - https://deb.b5.pm/debian/sparrow.key HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by jeanmarie** [benasse/sparrow#6]
Hello,
during installation, I got this error,
any suggestion?
fatal : [localhost] : ÉCHEC ! => [modifié] : faux, "msg" :  "Echec du téléchargement de la clé sur https://deb.b5.pm/debian/sparrow.key : Erreur HTTP 404 :  Non trouvé"}

**Comment by benasse** [comment]
Hi,

It should work if you try again.

The key was no longer present, I need to take the time to work on the scripts that manage the archive repositories, but it's complicated these days.

Regards,
