### ISSUE TITLE
error when install xivo-certs

### ISSUE THREAD

**Issue by jeanmarie** [benasse/sparrow#8]
hi,
Here the error retruned
TASK [b2bua : Install xivo-certs] **************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "'/usr/bin/apt-mark manual xivo-certs' failed: ", "rc": -9, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/pi/wazo-ansible/uc-engine.retry

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=54   changed=2    unreachable=0    failed=1

an idea ?

**Comment by benasse** [comment]
I never had this error, what does this commands return ?
```
apt install xivo-certs
apt-mark manual xivo-certs
```

**Comment by jeanmarie** [comment]
here the result

pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# apt install xivo-certs
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
xivo-certs est déjà la version la plus récente (20.04~20200322.174325.061e66e).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
root@raspberrypi:/home/pi# 
root@raspberrypi:/home/pi# apt-mark manual xivo-certs
xivo-certs était déjà marqué comme installé manuellement.
root@raspberrypi:/home/pi#

**Comment by benasse** [comment]
ok, and what happens if you restart the installation with ansible?
