### ISSUE TITLE
Request:  Don't Install NTP

### ISSUE THREAD

**Issue by firstkevinds** [benasse/sparrow#9]
Raspbian (and Debian) have systemd-timesyncd.service already installed and is much smaller than the full NTP..

Add
NTP= whatever.ntp.pool.you.want whatever2.ntp.server.you.want whatever3.ntp.pool.you.want 

to /etc/systemd/timesyncd.conf and restart the service

systemctl restart systemd-timesyncd.service

For keeping the time synced.

**Comment by benasse** [comment]
Does this have a significant impact on performance?
By default Wazo / Sparrow plays the role of ntp server for the hard phones that it manage.

**Comment by firstkevinds** [comment]
> Does this have a significant impact on performance?
> By default Wazo / Sparrow plays the role of ntp server for the hard phones that it manage.

30-50MB RAM

I wasn't aware that it by default it provided an NTP server for the phones.  
NTPSec would use a bit less resources (around half from memory)

**Comment by benasse** [comment]
You can make a pull request for this on the installer ?

Personally I am not to stray too far from what is done in upstream on wazo.
May be consider of doing the request first on the wazo repository : https://github.com/wazo-platform/wazo-ansible

If it doesn't suit them i might consider sparrow.
The ansible playbook and role that install sparrow are available here: https://github.com/benasse/wazo-ansible

Maybe you are not comfortable with ansible and just want to document it, feel free to make a pull request in this repository.
I would see this an addition in this part: https://sparrow.b5.pm/docs/tips/

**Comment by firstkevinds** [comment]
Alright.  I will try and do that this week.

Also to note, but not for this issue..

The timeouts that may happen during installs...  May not (all) be slow-SD card issues but the CPU over heating, so the Pi under-clocks itself to cool off, slowing down the install.

I've had this issue a few times when using fast SD cards.

Edit:  Alright, ansible is a different beast than I am used to playing with..  Neat, but different..  haha  Trying to adjust the timeouts during the initial install
